# This Makefile assumes that MinGW is in use and in the path
WINLIB := lib{{tolower .ModuleName}}shim.a
WINLIBDEP := {{filenamebase .OutputCFile}}.c
WINLIBOBJ := {{filenamebase .OutputCFile}}.o

CC := gcc
CCFLAGS := -std=c99

AR := ar
ARFLAGS := crf

$(WINLIB): $(WINLIBDEP)
	$(CC) $(CCFLAGS) -c $(WINLIBDEP) -o $(WINLIBOBJ) -I {{filepathpath .SourceHeader | convertslash}}
	$(AR) $(ARFLAGS) $(WINLIB) $(WINLIBOBJ)
